#!/bin/sh
git submodule init
git submodule update

if [ -f ~/.vimrc ] ;
    then
        echo "~/.vimrc exists, please backup first"
    else
        ln -s `pwd`/_vimrc ~/.vimrc
fi

if [ -d ~/.vim ] ;
    then
        echo "~/.vim exists, please backup first"
    else
        ln -s `pwd`/vimfiles/ ~/.vim
fi
